### ISSUE TITLE
HTTP endpoint that requires a JSON-formatted body

### ISSUE THREAD

**Issue by Ha5hBr0wn** [scalaj/scalaj-http#209]
I am trying to send a POST request, but get a HTTP status code of 400. Someone pointed out to me that it is probably because the encoding is not JSON. How can I change that?

**Comment by Ha5hBr0wn** [comment]
Also attaching the actual call here for reference

`
val response: HttpResponse[String] = Http(s"$endpoint/v2/orders").
      headers(Map(AlpacaInfo.key_header->key, AlpacaInfo.secret_header->secret)).
      params(Map("symbol"->symbol, "qty"->qty, "side"->side, "type"->`type`, "time_in_force"->time_in_force) ++ parameters).
      method("POST").asString
`

**Comment by fntz** [comment]
I see the options:

1. try to send 'Content-Type' in request
2. you do request in an incorrect way: because of `params` make URL like: '/v2/orders?symbol=symbol' but it should be a part of the request body. instead of `params`, you need to use [`postData`](https://github.com/scalaj/scalaj-http#post-raw-arraybyte-or-string-data-and-get-response-code) and decode your `Map` into `JSON`

**Comment by Ha5hBr0wn** [comment]
Yeah I didn't entirely understand the different ways parts of the message are encoded and thought I could use params to post with a JSON body. Thanks for the help!
