### ISSUE TITLE
Cannot GET with JSON -- like curl -X GET -d "jsonKey:jsonVal"

### ISSUE THREAD

**Issue by GeekSheikh** [scalaj/scalaj-http#222]
`.postData(json)` executes a post

`.postData(json).method("GET")` has no effect

It seems there's no way to execute a GET and send json query to the GET request. Please let me know if this is incorrect and if so, how can I do this?

Server accepts only JSON as query to GET endpoint so cannot use params

**Comment by hoffrocket** [comment]
try reversing-- `.method("GET").postData(json)`

**Comment by GeekSheikh** [comment]
Thanks. I did try that, no dice.
Same error -- see below

`HttpResponse({"error_code":"ENDPOINT_NOT_FOUND","message":"No API found for 'POST`

**Comment by alex-davies** [comment]
Im also encountering this same issue. Setting the method after the body seems to work with other methods like `DELETE` but `GET` always seems to revert back to a `POST`

**Comment by alex-davies** [comment]
This looks to be a 'feature' of the underlying HttpUrlConnection (https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1268-L1270) 

Unfortunately as this is part of the core library I don't think this is something scalaj-http will be able to do

**Comment by hoffrocket** [comment]
Hi, I'm no longer going to support the library, but as one last hurrah-- and because I wanted to see if it would be possible, I did commit a change to allow sending a body with a GET method. 
If you want to take advantage, and continue to use this library going forward, I would suggest copying the source code into your own repo. Otherwise, I would highly suggested migrating to an http library with active support.
