### ISSUE TITLE
ScalaJS compatibility

### ISSUE THREAD

**Issue by omidb** [scalaj/scalaj-http#84]
Hi,

I was wondering if it's possible to publish the lib for ScalaJS too. I guess the only problem is `faster-xml`dependency?

**Comment by hoffrocket** [comment]
Hi, ScalaJS is an unrelated project. You might find instructions for usage here: http://www.scala-js.org/doc/tutorial.html

**Comment by omidb** [comment]
what do you mean by unrelated? You can cross-compile a Scala library for both Scala and ScalaJS. My question what are the problems that you haven't done it yet. Is it because of `faster-xml` dependency ?

**Comment by hoffrocket** [comment]
Ah, sorry, I misunderstood the question. This is the first request I've had for that. I think it could be done, but I think it would be considerable amount of work. This library wraps java.net.HttpURLConnection and abstracts a lot of the nuances of that particular library. All that code would need to be rewritten for org.scalajs.dom.XMLHttpRequest. I could imagine having swappable backends for this library so that it could work with both.

**Comment by omidb** [comment]
Oh, I see. It's all Java. yeah, that would be a lot of work !
